name: Bank Unit Testing Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of your repository on the runner
    - uses: actions/checkout@v3
      # Configures runner for Java 17 JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      # Runs unit tests
    - name: Build with Maven
      run: mvn -B package --file pom.xml